services:
  # nginx
  web:
    build: 
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #php
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: "${BUILD_TARGET:-app}"
    volumes:
      # - /var/www/html/vendor
      - ./app:/usr/app
      - ./php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}
      # See https://xdebug.org/docs/all_settings#mode
      # XDEBUG_MODE: debug
      # XDEBUG_MODE: develop,debug
      # XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      XDEBUG_MODE: ${XDEBUG_MODE}
    extra_hosts:
        # Ensure that host.docker.internal is correctly defined on Linux
        - "host.docker.internal:host-gateway"
  #mariadb
  db:
    image: mariadb:lts
    ports:
      - "4406:3306"
    volumes:
      - mariadbdata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  #redis
  cache:
    image: redis:latest
volumes:
  mariadbdata: