services:
  # nginx
  web:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #php
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: app
    # volumes:
    #   - /var/www/html/vendor
    #   - ./app:/var/www/html
  #mariadb
  db:
    image: mariadb:lts
    ports:
      - "4406:3306"
    volumes:
      - mariadbdata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_USER: admin
      MARIADB_PASSWORD: 123456
      MARIADB_DATABASE: docker-php
volumes:
  mariadbdata: