services:
  # nginx
  web:
    build: 
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #php
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: "${BUILD_TARGET:-app}"
    volumes:
      # - /var/www/html/vendor
      - ./app:/usr/app
      - ./php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: ${XDEBUG_MODE}
  #mariadb
  db:
    ports:
      - "4406:3306"
    restart: unless-stopped
volumes:
  mariadbdata: