services:
  # nginx
  web:
    image: adaopedro/nginx-php:1.0
    ports:
      - "80:80"
  #php
  app:
    image: adaopedro/php-composer:1.0
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}
    extra_hosts:
        - "host.docker.internal:host-gateway"
  #mariadb
  db:
    image: mariadb:lts
    volumes:
      - mariadbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  #redis
  cache:
    image: redis:latest
volumes:
  mariadbdata: